### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [wKovacs64/mTorch#6]
With the last release ~2.5 years ago, do you still maintain this app, @wKovacs64? Will there be another release (as there were commits after the last)?

**Comment by wKovacs64** [comment]
Hey @IzzySoft - no, I don't have any plans for future releases. There are so many flashlight apps available and it's even baked into Android now, plus work has shifted my focus away from native Android development so I'm quite out of touch with the scene at the moment. I should probably throw an unmaintained message/badge at the top of the README or something.

Thanks for inquiring - I hope you got some use out of mTorch in the past. 🙂

**Comment by IzzySoft** [comment]
Thanks @wKovacs64 – and fully understandable. Good luck with your new projects! And yes, please add the info to the README (or archive the project – can be [un]done via its settings here at Github).

I still have your app [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.wkovacs64.mtorch), which was the reason for my inquiry. I will update its description accordingly, pointing here.

Thanks again for providing your app for free and as open source!

**Comment by wKovacs64** [comment]
Oh wow, that's cool. Thanks for doing that!

I will archive the repo now.
